export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE ='REGISTER_USER_FAILURE';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

// cheats type
export const CREATE_CHEAT_SUCCESS = 'CREATE_CHEAT_SUCCESS';
export const CREATE_CHEAT_FAILURE = 'CREATE_CHEAT_FAILURE';
export const EDIT_CHEAT_SUCCESS = 'EDIT_CHEAT_SUCCESS';
export const DELETE_CHEAT_SUCCESS = 'DELETE_CHEAT_SUCCESS';
export const DELETE_CHEAT_FAILURE = 'DELETE_CHEAT_FAILURE';
export const LOAD_CHEAT_SUCCESS = 'LOAD_CHEAT_SUCCESS';
export const LOAD_CHEAT_FAILURE = 'LOAD_CHEAT_FAILURE';
export const LOAD_SINGLE_CHEAT_SHEET_SUCCESS = 'LOAD_SINGLE_CHEAT_SHEET_SUCCESS';
export const LOAD_SINGLE_CHEAT_SHEET_FAILURE = 'LOAD_SINGLE_CHEAT_SHEET_FAILURE';
export const RESET_SINGLE_CHEAT_SHEET = 'RESET_SINGLE_CHEAT_SHEET';
export const SEARCH_CHEAT = 'SEARCH_CHEAT';

// commands
export const LOAD_COMMANDS_SUCCESS = 'LOAD_COMMANDS_SUCCESS';
export const LOAD_COMMANDS_FAILURE ='LOAD_COMMANDS_FAILURE';
export const ADD_COMMAND_SUCCESS = 'ADD_COMMAND_SUCCESS';
export const ADD_COMMAND_FAILURE = 'ADD_COMMAND_FAILURE';
export const EDIT_COMMAND_SUCCESS = 'EDIT_COMMAND_SUCCESS';
export const EDIT_COMMAND_FAILURE = 'EDIT_COMMAND_FAILURE';
export const DELETE_COMMAND_SUCCESS = 'DELETE_COMMAND_SUCCESS';
export const DELETE_COMMAND_FAILURE = 'DELETE_COMMAND_FAILURE';
export const FETCH_ONE_COMMAND_SUCCESS = 'FETCH_ONE_COMMAND_SUCCESS';
export const FETCH_ONE_COMMAND_FAILURE = 'FETCH_ONE_COMMAND_FAILURE';
