---
kind: Service
apiVersion: v1
metadata:
  name: feservice
spec:
  selector:
    app: cheat-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 3000
      nodePort: 30002
  type: LoadBalancer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheatappdeployment
  labels:
    app: cheat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cheat-app
  template:
    metadata:
      labels:
        app: cheat-app
    spec:
      containers:
        - name: cheat-app
          image: gidraff/cheat-app:v3
          ports:
            - containerPort: 3000