default: &defaults
  working_directory: ~/application
  docker:
    - image: circleci/node:10.13.0

cmd_restore_cache: &cmd_restore_cache
  restore_cache:
    keys: dependency-cache-{{ checksum "package.json" }}

cmd_save_cache: &cmd_save_cache
  save_cache: # special step to save the dependency cache
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - ./node_modules

cmd_update_npm: &cmd_update_npm
  run:
    name: Update npm
    command: 'sudo npm install -g npm@latest'

cmd_install_dependencies: &cmd_install_dependencies
  run:
          name: install-dependencies
          command: npm install


version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *cmd_restore_cache
      - *cmd_update_npm
      - *cmd_install_dependencies
      - *cmd_save_cache

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run: # run tests
          name: Run Test and Coverage
          command: |
            ./cc-test-reporter before-build
            npm test -- --coverage
            ./cc-test-reporter after-build --exit-code $?
